/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EE333;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author aless
 */
public class NewStudentPanel extends javax.swing.JPanel {
    
    
    // getters
    public String getStudentFirstName() {
    return jTextFirstName.getText();
}
    
    public String getStudentLastName() {
    return jTextLastName.getText();
}
    
    public String getStudentEmail() {
    return jTextEmail.getText();
}

public String getSelectedLevel() {
    return (String) jComboLevel.getSelectedItem();
}   

    /**
     * Creates new form NewStudentPanel
     */
    public NewStudentPanel() {
        initComponents();
    }
    
    // level options for panel calling...
    public void setLevelOptions(String[] levels) { 
    jComboLevel.removeAllItems();
    for (String level : levels) {
        jComboLevel.addItem(level);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jComboLevel = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckContact = new javax.swing.JCheckBox();
        jButtonSubmit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextStatus = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("ID:");

        jTextID.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Firstname:");

        jTextFirstName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFirstNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Lastname:");

        jTextLastName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLastNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Email:");

        jTextEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });

        jComboLevel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Level:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Contact:");

        jCheckContact.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jCheckContact.setText("Yes/No");
        jCheckContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckContactActionPerformed(evt);
            }
        });

        jButtonSubmit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Status:");

        jTextStatus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextStatus.setEnabled(false);
        jTextStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(233, 233, 233)
                        .addComponent(jTextEmail))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(189, 189, 189)
                        .addComponent(jTextLastName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                        .addComponent(jTextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckContact, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSubmit)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckContact)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>                        

    private void jTextIDActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void jTextFirstNameActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void jTextLastNameActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jCheckContactActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jTextStatusActionPerformed(java.awt.event.ActionEvent evt) {                                            

    }                                           

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:

        EE333.UserInfo NewUser = null;
        String ID;

        String FirstName;
        String LastName;
        String Email;
        String Level;
        EE333.UserLevel LevelAsEnum;
        boolean Contact;

        if (this.jTextID.getText().length() == 0 ){
            this.jTextStatus.setText("Error: Please enter an ID!");

        } else if (this.jTextFirstName.getText().length() == 0 ){
            this.jTextStatus.setText("Error:...");
        } else if (this.jTextLastName.getText().length() == 0 ){
            this.jTextStatus.setText("Error:...");
        } else if ((this.jTextEmail.getText().length() == 0 ) || ( EE333.UserInfo.IsEmail(this.jTextEmail.getText()) == false)) {
            this.jTextStatus.setText("Error: Please enter a valid Email!");
        } else if (jComboLevel.getSelectedIndex() == -1){
            this.jTextStatus.setText("Error: Please select a Level!");
        } else {
            ID = this.jTextID.getText();

            FirstName = this.jTextFirstName.getText();
            LastName = this.jTextLastName.getText();
            Email = this.jTextEmail.getText();
            Level = this.jComboLevel.getSelectedItem().toString();
            Contact = this.jCheckContact.isSelected(); // returns a boolean

            if (Level.equalsIgnoreCase("Undergrauate")){
                LevelAsEnum = EE333.UserLevel.Undergraduate;
            } else if (Level.equalsIgnoreCase("Graduate")){
                LevelAsEnum = EE333.UserLevel.Graduate;
            } else if (Level.equalsIgnoreCase("Professional")) {
                LevelAsEnum = EE333.UserLevel.Professional;
            } else if (Level.equalsIgnoreCase("Volunteer")){
                LevelAsEnum = EE333.UserLevel.Volunteer;
            } else {
                LevelAsEnum = EE333.UserLevel.Other;
            }

            NewUser = new EE333.UserInfo(ID, FirstName, LastName, Email, LevelAsEnum, Contact);

            EE333.UserInfoManager.ExportUserInfo(NewUser, "Users.csv", "csv"); // this calls to the controller

            // this is if everything is successful
            this.jTextStatus.setText("Note: Successfully exported!");

            // refers to the parent frame that you return to when the dialog is closed
            JOptionPane.showMessageDialog(this, "Note: Successful!"); // provides pop up box

            this.jTextID.setText("");

            this.jTextFirstName.setText("");
            this.jTextLastName.setText("");
            this.jTextEmail.setText("");
            this.jComboLevel.setSelectedIndex(0); // sets it back to the first value
            this.jCheckContact.setSelected(false);

        }
    }                                             


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JCheckBox jCheckContact;
    private javax.swing.JComboBox<String> jComboLevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFirstName;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextLastName;
    private javax.swing.JTextField jTextStatus;
    // End of variables declaration                   
}

