/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EE333;

import javax.swing.JOptionPane;

/**
 *
 * @author aless
 */
public class SRS_Welcome extends javax.swing.JFrame {

    /**
     * Creates new form SRS_Welcome
     */
    public SRS_Welcome() {
        initComponents();
        
        this.jComboLevel.removeAllItems(); // clears the combobox from anything that was already in it (programmatically)
        this.jComboLevel.addItem("Undergraduate");
        this.jComboLevel.addItem("Graduate");
        this.jComboLevel.addItem("Instructor");
        this.jComboLevel.addItem("Other");
    
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonNewStudent = new javax.swing.JButton();
        jButtonNewCourse = new javax.swing.JButton();
        jButtonUpdateStudentInfo = new javax.swing.JButton();
        jButtonUpdateCourseInfo = new javax.swing.JButton();
        jButtonCourseRegistration = new javax.swing.JButton();
        jButtonOptions = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonBackNewStudent = new javax.swing.JButton();
        newStudentPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jComboLevel = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckContact = new javax.swing.JCheckBox();
        jButtonSubmit = new javax.swing.JButton();
        jTextStatus = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonBackNewCourse = new javax.swing.JButton();
        jLabelDescription = new javax.swing.JLabel();
        jLabelCRN = new javax.swing.JLabel();
        jTextFieldDescription = new javax.swing.JTextField();
        jTextFieldCRN = new javax.swing.JTextField();
        jButtonCreateCourse = new javax.swing.JButton();
        jLabelSeats = new javax.swing.JLabel();
        jTextFieldSeats = new javax.swing.JTextField();
        jLabelNewCourseProfessor = new javax.swing.JLabel();
        jTextFieldNewCourseProfessor = new javax.swing.JTextField();
        jLabelNewCourseName = new javax.swing.JLabel();
        jTextFieldNewCourseName = new javax.swing.JTextField();
        jLabelNewCourseStatus = new javax.swing.JLabel();
        jTextNewCourseStatus = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButtonBackCourseRegistration = new javax.swing.JButton();
        jComboSCR = new javax.swing.JComboBox<>();
        jComboCourseRegistration = new javax.swing.JComboBox<>();
        jLabelStudentForCourseRegistration = new javax.swing.JLabel();
        jLabelChooseCourseRegistratin = new javax.swing.JLabel();
        jButtonRegisterCourse = new javax.swing.JButton();
        jTextCourseResitrationStatus = new javax.swing.JTextField();
        jLabelCourseRegistrationStatus = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButtonBackUpdateStudentInfo = new javax.swing.JButton();
        jLabelStudentFullName = new javax.swing.JLabel();
        jLabelNewFirstName = new javax.swing.JLabel();
        jLabelNewLastName = new javax.swing.JLabel();
        jLabelNewEmail = new javax.swing.JLabel();
        jComboBoxFullname = new javax.swing.JComboBox<>();
        jTextFieldNewFirstName = new javax.swing.JTextField();
        jTextFieldNewLastName = new javax.swing.JTextField();
        jTextFieldNewEmail = new javax.swing.JTextField();
        jButtonChangeStudentInfo = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButtonBackUpdateCourseInfo = new javax.swing.JButton();
        jLabelOldCourseName = new javax.swing.JLabel();
        jComboBoxCurrentCourseName = new javax.swing.JComboBox<>();
        jLabelNewProfessor = new javax.swing.JLabel();
        jLabelNewSeatCount = new javax.swing.JLabel();
        jLabelNewDescription = new javax.swing.JLabel();
        jTextFieldNewDescription = new javax.swing.JTextField();
        jTextFieldNewSeatCount = new javax.swing.JTextField();
        jTextFieldNewProfessor = new javax.swing.JTextField();
        jButtonChangeCourseInfo = new javax.swing.JButton();
        jLabelNewCRN = new javax.swing.JLabel();
        jTextFieldNewCRN = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jButtonBackOptions = new javax.swing.JButton();
        jLabelFileType = new javax.swing.JLabel();
        jComboFileType = new javax.swing.JComboBox<>();
        jLabelFolder = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonOptionsSubmit = new javax.swing.JButton();
        jLabelOptionsStatus = new javax.swing.JLabel();
        jTextOptionsStatus = new javax.swing.JTextField();

        jButton2.setText("jButton2");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 204));
        jTabbedPane1.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNewStudent.setBackground(new java.awt.Color(204, 255, 204));
        jButtonNewStudent.setText("New Student");
        jButtonNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewStudentActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 86, -1, -1));

        jButtonNewCourse.setBackground(new java.awt.Color(204, 255, 204));
        jButtonNewCourse.setText("New Course");
        jButtonNewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCourseActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNewCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 127, -1, -1));

        jButtonUpdateStudentInfo.setBackground(new java.awt.Color(204, 255, 204));
        jButtonUpdateStudentInfo.setText("Update Student Info");
        jButtonUpdateStudentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateStudentInfoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdateStudentInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 209, -1, -1));

        jButtonUpdateCourseInfo.setBackground(new java.awt.Color(204, 255, 204));
        jButtonUpdateCourseInfo.setText("Update Course Info");
        jButtonUpdateCourseInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateCourseInfoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdateCourseInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 250, -1, -1));

        jButtonCourseRegistration.setBackground(new java.awt.Color(204, 255, 204));
        jButtonCourseRegistration.setText("Course Registration");
        jButtonCourseRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCourseRegistrationActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCourseRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 168, -1, -1));

        jButtonOptions.setBackground(new java.awt.Color(204, 255, 204));
        jButtonOptions.setText("Options");
        jButtonOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOptionsActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 291, -1, -1));

        jTabbedPane1.addTab("Welcome ", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jButtonBackNewStudent.setBackground(new java.awt.Color(204, 255, 204));
        jButtonBackNewStudent.setText("Back");
        jButtonBackNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackNewStudentActionPerformed(evt);
            }
        });

        newStudentPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("ID:");

        jTextID.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextID.setEnabled(false);
        jTextID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Firstname:");

        jTextFirstName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFirstNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Lastname:");

        jTextLastName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLastNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Email:");

        jTextEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });

        jComboLevel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Level:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Contact:");

        jCheckContact.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jCheckContact.setText("Yes/No");
        jCheckContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckContactActionPerformed(evt);
            }
        });

        jButtonSubmit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jTextStatus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextStatus.setEnabled(false);
        jTextStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextStatusActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Status:");

        javax.swing.GroupLayout newStudentPanel1Layout = new javax.swing.GroupLayout(newStudentPanel1);
        newStudentPanel1.setLayout(newStudentPanel1Layout);
        newStudentPanel1Layout.setHorizontalGroup(
            newStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newStudentPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newStudentPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(233, 233, 233)
                        .addComponent(jTextEmail))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newStudentPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(189, 189, 189)
                        .addComponent(jTextLastName))
                    .addGroup(newStudentPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                        .addComponent(jTextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newStudentPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newStudentPanel1Layout.createSequentialGroup()
                        .addGroup(newStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(newStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckContact, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newStudentPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addComponent(jTextStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(newStudentPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jButtonSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newStudentPanel1Layout.setVerticalGroup(
            newStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newStudentPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckContact)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jButtonSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(newStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBackNewStudent)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(newStudentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newStudentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBackNewStudent))
        );

        jTabbedPane1.addTab("New Student", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jButtonBackNewCourse.setBackground(new java.awt.Color(204, 255, 204));
        jButtonBackNewCourse.setText("Back");
        jButtonBackNewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackNewCourseActionPerformed(evt);
            }
        });

        jLabelDescription.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelDescription.setText("Description:");

        jLabelCRN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelCRN.setText("CRN:");

        jTextFieldDescription.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jTextFieldCRN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextFieldCRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCRNActionPerformed(evt);
            }
        });

        jButtonCreateCourse.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonCreateCourse.setText("Create Course");
        jButtonCreateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateCourseActionPerformed(evt);
            }
        });

        jLabelSeats.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelSeats.setText("Seats:");

        jTextFieldSeats.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabelNewCourseProfessor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelNewCourseProfessor.setText("Professor:");

        jTextFieldNewCourseProfessor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabelNewCourseName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelNewCourseName.setText("Course Name :");

        jTextFieldNewCourseName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabelNewCourseStatus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelNewCourseStatus.setText("Status:");

        jTextNewCourseStatus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextNewCourseStatus.setEnabled(false);
        jTextNewCourseStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNewCourseStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButtonBackNewCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelNewCourseStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextNewCourseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jButtonCreateCourse))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelCRN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSeats, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDescription))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldDescription)
                                    .addComponent(jTextFieldCRN)
                                    .addComponent(jTextFieldSeats, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelNewCourseProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jTextFieldNewCourseProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabelNewCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNewCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewCourseName)
                    .addComponent(jTextFieldNewCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNewCourseProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNewCourseProfessor))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCRN)
                    .addComponent(jTextFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescription)
                    .addComponent(jTextFieldCRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSeats)
                    .addComponent(jTextFieldSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButtonCreateCourse)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButtonBackNewCourse))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNewCourseStatus)
                            .addComponent(jTextNewCourseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
        );

        jTabbedPane1.addTab("New Course", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        jButtonBackCourseRegistration.setBackground(new java.awt.Color(204, 255, 204));
        jButtonBackCourseRegistration.setText("Back");
        jButtonBackCourseRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackCourseRegistrationActionPerformed(evt);
            }
        });

        jComboSCR.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboSCR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboCourseRegistration.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboCourseRegistration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelStudentForCourseRegistration.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelStudentForCourseRegistration.setText("Student:");

        jLabelChooseCourseRegistratin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelChooseCourseRegistratin.setText("Course:");

        jButtonRegisterCourse.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonRegisterCourse.setText("Register");
        jButtonRegisterCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterCourseActionPerformed(evt);
            }
        });

        jTextCourseResitrationStatus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextCourseResitrationStatus.setEnabled(false);
        jTextCourseResitrationStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCourseResitrationStatusActionPerformed(evt);
            }
        });

        jLabelCourseRegistrationStatus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelCourseRegistrationStatus.setText("Status:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButtonBackCourseRegistration)
                .addGap(0, 860, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelStudentForCourseRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboSCR, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCourseRegistrationStatus)
                            .addComponent(jLabelChooseCourseRegistratin, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addComponent(jComboCourseRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(121, 121, 121))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jTextCourseResitrationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(jButtonRegisterCourse)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStudentForCourseRegistration)
                    .addComponent(jComboSCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelChooseCourseRegistratin)
                    .addComponent(jComboCourseRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButtonRegisterCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCourseRegistrationStatus)
                    .addComponent(jTextCourseResitrationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jButtonBackCourseRegistration))
        );

        jTabbedPane1.addTab("Course Registration", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        jButtonBackUpdateStudentInfo.setBackground(new java.awt.Color(204, 255, 204));
        jButtonBackUpdateStudentInfo.setText("Back");
        jButtonBackUpdateStudentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackUpdateStudentInfoActionPerformed(evt);
            }
        });

        jLabelStudentFullName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelStudentFullName.setText("Fullname:");

        jLabelNewFirstName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelNewFirstName.setText("New Firstname:");

        jLabelNewLastName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelNewLastName.setText("New Lastname:");

        jLabelNewEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelNewEmail.setText("New Email:");

        jComboBoxFullname.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBoxFullname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldNewFirstName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jTextFieldNewLastName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jTextFieldNewEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jButtonChangeStudentInfo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonChangeStudentInfo.setText("Change Student Info");
        jButtonChangeStudentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeStudentInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jButtonBackUpdateStudentInfo)
                .addGap(0, 860, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jButtonChangeStudentInfo))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldNewFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(117, 117, 117)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelNewLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelNewEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabelNewFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabelStudentFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(91, 91, 91)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldNewLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                        .addComponent(jTextFieldNewEmail)))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(115, 115, 115)
                                    .addComponent(jComboBoxFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStudentFullName)
                    .addComponent(jComboBoxFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewFirstName)
                    .addComponent(jTextFieldNewFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewLastName)
                    .addComponent(jTextFieldNewLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewEmail)
                    .addComponent(jTextFieldNewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButtonChangeStudentInfo)
                .addGap(46, 46, 46)
                .addComponent(jButtonBackUpdateStudentInfo))
        );

        jTabbedPane1.addTab("Update Student Info", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));

        jButtonBackUpdateCourseInfo.setBackground(new java.awt.Color(204, 255, 204));
        jButtonBackUpdateCourseInfo.setText("Back");
        jButtonBackUpdateCourseInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackUpdateCourseInfoActionPerformed(evt);
            }
        });

        jLabelOldCourseName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelOldCourseName.setText("Course Name:");

        jComboBoxCurrentCourseName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBoxCurrentCourseName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelNewProfessor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelNewProfessor.setText("New Professor:");

        jLabelNewSeatCount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelNewSeatCount.setText("New Seat Count:");

        jLabelNewDescription.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelNewDescription.setText("New Description:");

        jTextFieldNewDescription.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jTextFieldNewSeatCount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jTextFieldNewProfessor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jButtonChangeCourseInfo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonChangeCourseInfo.setText("Change Course Info");
        jButtonChangeCourseInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeCourseInfoActionPerformed(evt);
            }
        });

        jLabelNewCRN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelNewCRN.setText("New CRN:");

        jTextFieldNewCRN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButtonBackUpdateCourseInfo)
                .addGap(0, 860, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNewSeatCount)
                            .addComponent(jTextFieldNewDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelNewProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelOldCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNewSeatCount)
                                    .addComponent(jLabelNewCRN, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNewDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNewCRN, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jComboBoxCurrentCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldNewProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonChangeCourseInfo)
                .addGap(318, 318, 318))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOldCourseName)
                    .addComponent(jComboBoxCurrentCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewProfessor)
                    .addComponent(jTextFieldNewProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewCRN)
                    .addComponent(jTextFieldNewCRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewSeatCount)
                    .addComponent(jTextFieldNewSeatCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewDescription)
                    .addComponent(jTextFieldNewDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jButtonChangeCourseInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButtonBackUpdateCourseInfo))
        );

        jTabbedPane1.addTab("Update Course Info", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));

        jButtonBackOptions.setBackground(new java.awt.Color(204, 255, 204));
        jButtonBackOptions.setText("Back");
        jButtonBackOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackOptionsActionPerformed(evt);
            }
        });

        jLabelFileType.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelFileType.setText("File Type:");

        jComboFileType.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboFileType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelFolder.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelFolder.setText("Folder:");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jButtonOptionsSubmit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonOptionsSubmit.setText("Submit");
        jButtonOptionsSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOptionsSubmitActionPerformed(evt);
            }
        });

        jLabelOptionsStatus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelOptionsStatus.setText("Status:");

        jTextOptionsStatus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextOptionsStatus.setEnabled(false);
        jTextOptionsStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextOptionsStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jButtonBackOptions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelOptionsStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextOptionsStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabelFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabelFileType, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonOptionsSubmit)
                            .addComponent(jComboFileType, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFolder)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFileType)
                    .addComponent(jComboFileType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jButtonBackOptions))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOptionsSubmit)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOptionsStatus)
                            .addComponent(jTextOptionsStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
        );

        jTabbedPane1.addTab("Options", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewStudentActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        
    }//GEN-LAST:event_jButtonNewStudentActionPerformed

    private void jButtonBackNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackNewStudentActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonBackNewStudentActionPerformed

    private void jButtonBackNewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackNewCourseActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonBackNewCourseActionPerformed

    private void jButtonBackUpdateCourseInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackUpdateCourseInfoActionPerformed
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonBackUpdateCourseInfoActionPerformed

    private void jButtonBackUpdateStudentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackUpdateStudentInfoActionPerformed
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonBackUpdateStudentInfoActionPerformed

    private void jButtonBackCourseRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackCourseRegistrationActionPerformed
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonBackCourseRegistrationActionPerformed

    private void jButtonNewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCourseActionPerformed
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButtonNewCourseActionPerformed

    private void jButtonCourseRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCourseRegistrationActionPerformed
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButtonCourseRegistrationActionPerformed

    private void jButtonUpdateStudentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateStudentInfoActionPerformed
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jButtonUpdateStudentInfoActionPerformed

    private void jButtonUpdateCourseInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateCourseInfoActionPerformed
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_jButtonUpdateCourseInfoActionPerformed

    private void jButtonOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOptionsActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_jButtonOptionsActionPerformed

    private void jButtonBackOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackOptionsActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonBackOptionsActionPerformed

    private void jTextFieldCRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCRNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCRNActionPerformed

    private void jButtonCreateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCreateCourseActionPerformed

    private void jTextIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIDActionPerformed

    private void jTextFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFirstNameActionPerformed

    private void jTextLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLastNameActionPerformed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void jCheckContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckContactActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // TODO add your handling code here:

        EE333.UserInfo NewUser = null;
        String ID;

        String FirstName;
        String LastName;
        String Email;
        String Level;
        EE333.UserLevel LevelAsEnum;
        boolean Contact;

      
           

        if (this.jTextFirstName.getText().length() == 0 ){
            this.jTextStatus.setText("Error: Please enter a FirstName");
        } else if (this.jTextLastName.getText().length() == 0 ){
            this.jTextStatus.setText("Error: Please enter a LastName");
        } else if ((this.jTextEmail.getText().length() == 0 ) || ( EE333.UserInfo.IsEmail(this.jTextEmail.getText()) == false)) {
            this.jTextStatus.setText("Error: Please enter a valid Email!");
        } else if (jComboLevel.getSelectedIndex() == -1){
            this.jTextStatus.setText("Error: Please select a Level!");
        } else {
            ID = this.jTextID.getText();

            FirstName = this.jTextFirstName.getText();
            LastName = this.jTextLastName.getText();
            Email = this.jTextEmail.getText();
            Level = this.jComboLevel.getSelectedItem().toString();
            Contact = this.jCheckContact.isSelected(); // returns a boolean

            if (Level.equalsIgnoreCase("Undergrauate")){
                LevelAsEnum = EE333.UserLevel.Undergraduate;
            } else if (Level.equalsIgnoreCase("Graduate")){
                LevelAsEnum = EE333.UserLevel.Graduate;
            } else if (Level.equalsIgnoreCase("Professional")) {
                LevelAsEnum = EE333.UserLevel.Professional;
            } else if (Level.equalsIgnoreCase("Volunteer")){
                LevelAsEnum = EE333.UserLevel.Volunteer;
            } else {
                LevelAsEnum = EE333.UserLevel.Other;
            }

            NewUser = new EE333.UserInfo(ID, FirstName, LastName, Email, LevelAsEnum, Contact);

            EE333.UserInfoManager.ExportUserInfo(NewUser, "Users.csv", "csv"); // this calls to the controller

            // this is if everything is successful
            this.jTextStatus.setText("Note: Successfully exported!");

            // refers to the parent frame that you return to when the dialog is closed
            JOptionPane.showMessageDialog(this, "Note: Successful!"); // provides pop up box

            this.jTextID.setText("");

            this.jTextFirstName.setText("");
            this.jTextLastName.setText("");
            this.jTextEmail.setText("");
            this.jComboLevel.setSelectedIndex(0); // sets it back to the first value
            this.jCheckContact.setSelected(false);

        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jTextStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextStatusActionPerformed

    }//GEN-LAST:event_jTextStatusActionPerformed

    private void jButtonRegisterCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegisterCourseActionPerformed

    private void jButtonChangeStudentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeStudentInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonChangeStudentInfoActionPerformed

    private void jButtonChangeCourseInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeCourseInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonChangeCourseInfoActionPerformed

    private void jTextNewCourseStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNewCourseStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNewCourseStatusActionPerformed

    private void jTextOptionsStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextOptionsStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextOptionsStatusActionPerformed

    private void jButtonOptionsSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOptionsSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOptionsSubmitActionPerformed

    private void jTextCourseResitrationStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCourseResitrationStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCourseResitrationStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SRS_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SRS_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SRS_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SRS_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SRS_Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBackCourseRegistration;
    private javax.swing.JButton jButtonBackNewCourse;
    private javax.swing.JButton jButtonBackNewStudent;
    private javax.swing.JButton jButtonBackOptions;
    private javax.swing.JButton jButtonBackUpdateCourseInfo;
    private javax.swing.JButton jButtonBackUpdateStudentInfo;
    private javax.swing.JButton jButtonChangeCourseInfo;
    private javax.swing.JButton jButtonChangeStudentInfo;
    private javax.swing.JButton jButtonCourseRegistration;
    private javax.swing.JButton jButtonCreateCourse;
    private javax.swing.JButton jButtonNewCourse;
    private javax.swing.JButton jButtonNewStudent;
    private javax.swing.JButton jButtonOptions;
    private javax.swing.JButton jButtonOptionsSubmit;
    private javax.swing.JButton jButtonRegisterCourse;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JButton jButtonUpdateCourseInfo;
    private javax.swing.JButton jButtonUpdateStudentInfo;
    private javax.swing.JCheckBox jCheckContact;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JComboBox<String> jComboBoxCurrentCourseName;
    private javax.swing.JComboBox<String> jComboBoxFullname;
    private javax.swing.JComboBox<String> jComboCourseRegistration;
    private javax.swing.JComboBox<String> jComboFileType;
    private javax.swing.JComboBox<String> jComboLevel;
    private javax.swing.JComboBox<String> jComboSCR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCRN;
    private javax.swing.JLabel jLabelChooseCourseRegistratin;
    private javax.swing.JLabel jLabelCourseRegistrationStatus;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelFileType;
    private javax.swing.JLabel jLabelFolder;
    private javax.swing.JLabel jLabelNewCRN;
    private javax.swing.JLabel jLabelNewCourseName;
    private javax.swing.JLabel jLabelNewCourseProfessor;
    private javax.swing.JLabel jLabelNewCourseStatus;
    private javax.swing.JLabel jLabelNewDescription;
    private javax.swing.JLabel jLabelNewEmail;
    private javax.swing.JLabel jLabelNewFirstName;
    private javax.swing.JLabel jLabelNewLastName;
    private javax.swing.JLabel jLabelNewProfessor;
    private javax.swing.JLabel jLabelNewSeatCount;
    private javax.swing.JLabel jLabelOldCourseName;
    private javax.swing.JLabel jLabelOptionsStatus;
    private javax.swing.JLabel jLabelSeats;
    private javax.swing.JLabel jLabelStudentForCourseRegistration;
    private javax.swing.JLabel jLabelStudentFullName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextCourseResitrationStatus;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCRN;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldNewCRN;
    private javax.swing.JTextField jTextFieldNewCourseName;
    private javax.swing.JTextField jTextFieldNewCourseProfessor;
    private javax.swing.JTextField jTextFieldNewDescription;
    private javax.swing.JTextField jTextFieldNewEmail;
    private javax.swing.JTextField jTextFieldNewFirstName;
    private javax.swing.JTextField jTextFieldNewLastName;
    private javax.swing.JTextField jTextFieldNewProfessor;
    private javax.swing.JTextField jTextFieldNewSeatCount;
    private javax.swing.JTextField jTextFieldSeats;
    private javax.swing.JTextField jTextFirstName;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextLastName;
    private javax.swing.JTextField jTextNewCourseStatus;
    private javax.swing.JTextField jTextOptionsStatus;
    private javax.swing.JTextField jTextStatus;
    private javax.swing.JPanel newStudentPanel1;
    // End of variables declaration//GEN-END:variables
}
