/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EE333;

/**
 *
 * @author aless
 */
public class SRS_Welcome extends javax.swing.JFrame {

    /**
     * Creates new form SRS_Welcome
     */
    public SRS_Welcome() {
        
        initComponents();
        
    // Charlotte 4/22 2:12PM - New Student Variables    
        String[] levelOptions = {"Undergraduate", "Graduate", "Instructor", "Other"};
        newStudentPanel1.setLevelOptions(levelOptions);
        
    String StudentFirstName = newStudentPanel1.getStudentFirstName();
    String StudentLastName = newStudentPanel1.getStudentLastName();
    String StudentEmail = newStudentPanel1.getStudentEmail();
    String StudentLevel = newStudentPanel1.getSelectedLevel();
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonNewStudent = new javax.swing.JButton();
        jButtonNewCourse = new javax.swing.JButton();
        jButtonUpdateStudentInfo = new javax.swing.JButton();
        jButtonUpdateCourseInfo = new javax.swing.JButton();
        jButtonCourseRegistration = new javax.swing.JButton();
        jButtonOptions = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonBackNewStudent = new javax.swing.JButton();
        newStudentPanel1 = new EE333.NewStudentPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButtonBackNewCourse = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonBackCourseRegistration = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonBackUpdateStudentInfo = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButtonBackUpdateCourseInfo = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButtonBackOptions = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNewStudent.setText("New Student");
        jButtonNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewStudentActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 86, -1, -1));

        jButtonNewCourse.setText("New Course");
        jButtonNewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCourseActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNewCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 127, -1, -1));

        jButtonUpdateStudentInfo.setText("Update Student Info");
        jButtonUpdateStudentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateStudentInfoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdateStudentInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 209, -1, -1));

        jButtonUpdateCourseInfo.setText("Update Course Info");
        jButtonUpdateCourseInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateCourseInfoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdateCourseInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 250, -1, -1));

        jButtonCourseRegistration.setText("Course Registration");
        jButtonCourseRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCourseRegistrationActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCourseRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 168, -1, -1));

        jButtonOptions.setText("Options");
        jButtonOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOptionsActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 291, -1, -1));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 890, 440));

        jTabbedPane1.addTab("Welcome ", jPanel1);

        jButtonBackNewStudent.setText("Back");
        jButtonBackNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackNewStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(newStudentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBackNewStudent))
                .addGap(0, 246, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(newStudentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButtonBackNewStudent))
        );

        jTabbedPane1.addTab("New Student", jPanel2);

        jTextField1.setText("Hi :)");

        jButtonBackNewCourse.setText("Back");
        jButtonBackNewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackNewCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(613, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButtonBackNewCourse)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(jButtonBackNewCourse))
        );

        jTabbedPane1.addTab("New Course", jPanel3);

        jButtonBackCourseRegistration.setText("Back");
        jButtonBackCourseRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackCourseRegistrationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButtonBackCourseRegistration)
                .addGap(0, 828, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 427, Short.MAX_VALUE)
                .addComponent(jButtonBackCourseRegistration))
        );

        jTabbedPane1.addTab("Course Registration", jPanel4);

        jButtonBackUpdateStudentInfo.setText("Back");
        jButtonBackUpdateStudentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackUpdateStudentInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jButtonBackUpdateStudentInfo)
                .addGap(0, 828, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 427, Short.MAX_VALUE)
                .addComponent(jButtonBackUpdateStudentInfo))
        );

        jTabbedPane1.addTab("Update Student Info", jPanel5);

        jButtonBackUpdateCourseInfo.setText("Back");
        jButtonBackUpdateCourseInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackUpdateCourseInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButtonBackUpdateCourseInfo)
                .addGap(0, 828, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 427, Short.MAX_VALUE)
                .addComponent(jButtonBackUpdateCourseInfo))
        );

        jTabbedPane1.addTab("Update Course Info", jPanel6);

        jButtonBackOptions.setText("Back");
        jButtonBackOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackOptionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jButtonBackOptions)
                .addGap(0, 828, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 427, Short.MAX_VALUE)
                .addComponent(jButtonBackOptions))
        );

        jTabbedPane1.addTab("Options", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>                        

    private void jButtonNewStudentActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        
    }                                                 

    private void jButtonBackNewStudentActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(0);
    }                                                     

    private void jButtonBackNewCourseActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }                                                    

    private void jButtonBackUpdateCourseInfoActionPerformed(java.awt.event.ActionEvent evt) {                                                            
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(0);
    }                                                           

    private void jButtonBackUpdateStudentInfoActionPerformed(java.awt.event.ActionEvent evt) {                                                             
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(0);
    }                                                            

    private void jButtonBackCourseRegistrationActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(0);
    }                                                             

    private void jButtonNewCourseActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(2);
    }                                                

    private void jButtonCourseRegistrationActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(3);
    }                                                         

    private void jButtonUpdateStudentInfoActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(4);
    }                                                        

    private void jButtonUpdateCourseInfoActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(5);
    }                                                       

    private void jButtonOptionsActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(6);
    }                                              

    private void jButtonBackOptionsActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }                                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SRS_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SRS_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SRS_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SRS_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SRS_Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBackCourseRegistration;
    private javax.swing.JButton jButtonBackNewCourse;
    private javax.swing.JButton jButtonBackNewStudent;
    private javax.swing.JButton jButtonBackOptions;
    private javax.swing.JButton jButtonBackUpdateCourseInfo;
    private javax.swing.JButton jButtonBackUpdateStudentInfo;
    private javax.swing.JButton jButtonCourseRegistration;
    private javax.swing.JButton jButtonNewCourse;
    private javax.swing.JButton jButtonNewStudent;
    private javax.swing.JButton jButtonOptions;
    private javax.swing.JButton jButtonUpdateCourseInfo;
    private javax.swing.JButton jButtonUpdateStudentInfo;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private EE333.NewStudentPanel newStudentPanel1;
    // End of variables declaration                   
}
